version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password